### ISSUE TITLE
demo.apk

### ISSUE THREAD

**Issue by Guowj** [niniloveyou/StateButton#1]
demo.apk 下载安装后闪退！！

**Comment by Saxxhw** [comment]
11-16 19:18:20.377 17435-17435/deadline.statebutton E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: deadline.statebutton, PID: 17435
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{deadline.statebutton/deadline.statebutton.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2333)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2384)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5300)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2195)
                                                                          at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2103)
                                                                          at android.content.res.Resources.getDrawable(Resources.java:720)
                                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
                                                                          at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                          at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
                                                                          at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
                                                                          at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
                                                                          at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
                                                                          at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                          at deadline.statebutton.MainActivity.onCreate(MainActivity.java:21)
                                                                          at android.app.Activity.performCreate(Activity.java:5280)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2384) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5300) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                          at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:935)
                                                                          at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
                                                                          at android.content.res.Resources.createFromXml(Resources.java:2821)
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2191)
                                                                          at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393) 
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:2103) 
                                                                          at android.content.res.Resources.getDrawable(Resources.java:720) 
                                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689) 
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186) 
                                                                          at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77) 
                                                                          at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41) 
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193) 
                                                                          at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173) 
                                                                          at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511) 
                                                                          at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                                          at deadline.statebutton.MainActivity.onCreate(MainActivity.java:21) 
                                                                          at android.app.Activity.performCreate(Activity.java:5280) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2384) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                          at android.os.Looper.loop(Looper.java:193) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5300) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by Saxxhw** [comment]
上面是错误信息

**Comment by niniloveyou** [comment]
stateButton是继承v7包里面的AppCompatButton, 看错误日志是缺少v19/abc_ic_ab_back_material.xml这个文件，如果影响正常使用了，也可以直接继承button， 然后构造函数里面那个android.xxxxx.R.button_style, 换成0，就可以了。 我估计是support包版本不同造成的，另外，我没修改默认的最低版本，这个demo的最低版本为4.0.
